export const quizData = [
  {
    topic: "DSA",
    subtopics: [
      "Arrays",
      "Linked Lists",
      "Stacks",
      "Queues",
      "Trees",
      "Graphs",
      "Sorting Algorithms",
      "Searching Algorithms",
      "Hashing",
      "Dynamic Programming",
      "Greedy Algorithms",
      "Bit Manipulation",
      "Recursion",
      "Divide and Conquer",
      "Backtracking",
      "Heap Data Structure",
      "Priority Queues",
      "Graph Algorithms (DFS, BFS)",
      "Segment Trees",
      "Trie Data Structure",
    ],
  },
  {
    topic: "Frontend",
    subtopics: ["HTML", "CSS", "JavaScript", "React"],
  },
  {
    topic: "Backend",
    subtopics: ["Node.js", "Express.js"],
  },
];
